name: Basic Checks for Static Website

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-html:
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install htmlhint
        run: npm install -g htmlhint
      - name: Run htmlhint on HTML files
        run: htmlhint "/*.html"

  check-css-js:
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ Checkout code
        uses: actions/checkout@v4

      - name: ðŸ“‚ List CSS and JS files
        run: |
          echo "CSS files:"
          find . -name "*.css"
          echo "JS files:"
          findÂ .Â -nameÂ "*.js"
